//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub mod prelude;

pub mod coordinates;
pub mod material_planets;
pub mod material_stars;
pub mod materials;
pub mod objects;
pub mod planets;
pub mod spacecrafts;
pub mod stars;
pub mod users;
