//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.4

pub use super::coordinates::Entity as Coordinates;
pub use super::material_planets::Entity as MaterialPlanets;
pub use super::material_stars::Entity as MaterialStars;
pub use super::materials::Entity as Materials;
pub use super::objects::Entity as Objects;
pub use super::planets::Entity as Planets;
pub use super::spacecrafts::Entity as Spacecrafts;
pub use super::stars::Entity as Stars;
pub use super::users::Entity as Users;
