/**
 * This file was auto-generated by @openapi-qraft/cli.
 * Do not make direct changes to the file.
 */

import { PingService, pingService } from "./PingService";
import { HealthService, healthService } from "./HealthService";
import { ApiService, apiService } from "./ApiService";
export type Services = {
    ping: PingService;
    health: HealthService;
    api: ApiService;
};
export const services = {
    ping: pingService,
    health: healthService,
    api: apiService
} as const;
